CREATE TYPE "UserStatus" AS ENUM ('PENDING', 'AVAILABLE', 'CHANGE_PASSWORD');

ALTER TABLE "users" ADD COLUMN "status" "UserStatus" NOT NULL DEFAULT 'AVAILABLE';

ALTER TABLE "users" ALTER COLUMN "status" SET DEFAULT 'PENDING';
